package git

import (
	"errors"
	"regexp"
	"strings"

	"devora/internal/process"
)

// maxBranchLength caps branch names generated by GenerateBranchName.
const maxBranchLength = 70

// unnamedSlug is the fallback slug when taskName produces no ASCII-alphanumeric
// characters (empty, all-whitespace, or pure non-ASCII input).
const unnamedSlug = "unnamed"

// nonAlphaNum collapses runs of non-alphanumeric ASCII characters into a single
// dash. Used by GenerateBranchName.
var nonAlphaNum = regexp.MustCompile(`[^0-9a-zA-Z]+`)

// detachedHeadMarker identifies stderr from `git symbolic-ref --short HEAD`
// when HEAD is not a symbolic ref (i.e., detached).
const detachedHeadMarker = "ref HEAD is not a symbolic ref"

// ProtectedBranches is the fixed list of branch names debi refuses to operate
// on via submit/close. Shared so callers and tests can reference it directly.
var ProtectedBranches = []string{"main", "master", "develop"}

// CurrentBranchOrDetached returns the current branch name, or "" if HEAD is
// detached. Uses `git symbolic-ref --short HEAD`. When detached, git exits
// non-zero with "fatal: ref HEAD is not a symbolic ref"; that's expected and
// returns ("", nil). Any other error (not in a repo, etc.) propagates.
func CurrentBranchOrDetached(opts ...process.ExecOption) (string, error) {
	output, err := process.GetOutput(
		[]string{"git", "symbolic-ref", "--short", "HEAD"},
		opts...,
	)
	if err == nil {
		return output, nil
	}
	var verr *process.VerboseExecError
	if errors.As(err, &verr) && strings.Contains(verr.Stderr, detachedHeadMarker) {
		return "", nil
	}
	return "", err
}

// IsProtectedBranch reports whether branch appears in ProtectedBranches.
func IsProtectedBranch(branch string) bool {
	for _, p := range ProtectedBranches {
		if branch == p {
			return true
		}
	}
	return false
}

// AddAllAndCommit stages all changes and creates a commit with message.
// Defaults to passthrough (user sees git's output); pass process.WithSilent()
// to suppress stdout/stderr.
func AddAllAndCommit(message string, opts ...process.ExecOption) error {
	if err := process.RunPassthrough([]string{"git", "add", "."}, opts...); err != nil {
		return err
	}
	return process.RunPassthrough([]string{"git", "commit", "-m", message}, opts...)
}

// CreateAndCheckoutBranch creates a new branch from HEAD and switches to it.
func CreateAndCheckoutBranch(name string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "checkout", "-b", name}, opts...)
}

// PushSetUpstream pushes branch to origin and sets it as the upstream.
func PushSetUpstream(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "push", "--set-upstream", "origin", branch}, opts...)
}

// DeleteRemoteBranch deletes branch from origin.
func DeleteRemoteBranch(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "push", "origin", "--delete", branch}, opts...)
}

// DeleteLocalBranch force-deletes the local branch.
func DeleteLocalBranch(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "branch", "-D", branch}, opts...)
}

// HasLocalBranch reports whether branch exists locally, using
// `git rev-parse --verify <branch>`.
func HasLocalBranch(branch string, opts ...process.ExecOption) bool {
	_, err := process.GetOutput(
		[]string{"git", "rev-parse", "--verify", branch},
		opts...,
	)
	return err == nil
}

// HasRemoteBranch reports whether branch exists on origin, using
// `git ls-remote --exit-code --heads origin <branch>`.
func HasRemoteBranch(branch string, opts ...process.ExecOption) bool {
	_, err := process.GetOutput(
		[]string{"git", "ls-remote", "--exit-code", "--heads", "origin", branch},
		opts...,
	)
	return err == nil
}

// SetBranchConfig writes branch.<branch>.<key>=<value> to local git config.
func SetBranchConfig(branch, key, value string, opts ...process.ExecOption) error {
	return process.RunPassthrough(
		[]string{"git", "config", "--local", branchConfigKey(branch, key), value},
		opts...,
	)
}

// GetBranchConfig returns the value for branch.<branch>.<key>, or "" if unset.
// Uses `git config --get --default "" branch.<branch>.<key>`, which exits 0
// with empty output when the key is missing (requires git 2.18+).
func GetBranchConfig(branch, key string, opts ...process.ExecOption) (string, error) {
	return process.GetOutput(
		[]string{"git", "config", "--get", "--default", "", branchConfigKey(branch, key)},
		opts...,
	)
}

// branchConfigKey formats a git config key of the form branch.<branch>.<key>.
func branchConfigKey(branch, key string) string {
	return "branch." + branch + "." + key
}

// FetchOrigin fetches from origin in passthrough mode.
func FetchOrigin(opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "fetch", "origin"}, opts...)
}

// CheckoutDetach checks out ref. Callers pass a ref such as
// "origin/<default>" to land in detached HEAD.
func CheckoutDetach(ref string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "checkout", ref}, opts...)
}

// GenerateBranchName produces "<prefix>-<slug>" where <slug> is a dash-
// separated, lowercase, ASCII-alphanumeric distillation of taskName:
// non-alphanumerics collapse to a single '-', leading/trailing '-' are
// trimmed, and the result is capped at 70 characters total (with trailing
// '-' trimmed after truncation). If the slug derived from taskName is empty
// (e.g., empty input or all non-ASCII), it falls back to "unnamed".
func GenerateBranchName(prefix, taskName string) string {
	slug := slugify(taskName)
	if slug == "" {
		slug = unnamedSlug
	}

	var result string
	if prefix == "" {
		result = slug
	} else {
		result = prefix + "-" + slug
	}
	result = strings.ToLower(result)
	result = nonAlphaNum.ReplaceAllString(result, "-")
	result = strings.Trim(result, "-")

	if len(result) > maxBranchLength {
		result = result[:maxBranchLength]
		result = strings.TrimRight(result, "-")
	}
	return result
}

// slugify lowercases and collapses runs of non-alphanumerics in s into
// single dashes, trimming leading and trailing dashes. Used to check
// whether taskName is entirely non-ASCII-alphanumeric.
func slugify(s string) string {
	lower := strings.ToLower(s)
	replaced := nonAlphaNum.ReplaceAllString(lower, "-")
	return strings.Trim(replaced, "-")
}
