package git

import (
	"errors"
	"os/exec"
	"regexp"
	"strings"

	"devora/internal/process"
)

const maxBranchLength = 70 // caps branch names generated by GenerateBranchName.

const unnamedSlug = "unnamed" // The fallback when taskName produces no ASCII-alphanumeric characters (empty, all-whitespace, or pure non-ASCII input)

var nonAlphaNum = regexp.MustCompile(`[^0-9a-zA-Z]+`)

const detachedHeadMarker = "ref HEAD is not a symbolic ref" // identifies stderr from `git symbolic-ref --short HEAD` when HEAD is not a symbolic ref (i.e., detached)

func CurrentBranchOrDetached(opts ...process.ExecOption) (string, error) {
	output, err := process.GetOutput(
		[]string{"git", "symbolic-ref", "--short", "HEAD"},
		opts...,
	)
	if err == nil {
		return output, nil
	}
	var verr *process.VerboseExecError
	if errors.As(err, &verr) && strings.Contains(verr.Stderr, detachedHeadMarker) {
		return "", nil
	}
	return "", err
}

func AddAllAndCommit(message string, opts ...process.ExecOption) error {
	if err := process.RunPassthrough([]string{"git", "add", "."}, opts...); err != nil {
		return err
	}
	return process.RunPassthrough([]string{"git", "commit", "-m", message}, opts...)
}

func CreateAndCheckoutBranch(name string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "checkout", "-b", name}, opts...)
}

func PushSetUpstream(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "push", "--set-upstream", "origin", branch}, opts...)
}

func DeleteRemoteBranch(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "push", "origin", "--delete", branch}, opts...)
}

func DeleteLocalBranch(branch string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "branch", "-D", branch}, opts...)
}

func HasLocalBranch(branch string, opts ...process.ExecOption) bool {
	_, err := process.GetOutput(
		[]string{"git", "rev-parse", "--verify", branch},
		opts...,
	)
	return err == nil
}

func HasRemoteBranch(branch string, opts ...process.ExecOption) bool {
	_, err := process.GetOutput(
		[]string{"git", "ls-remote", "--exit-code", "--heads", "origin", branch},
		opts...,
	)
	return err == nil
}

func SetBranchConfig(branch, key, value string, opts ...process.ExecOption) error {
	return process.RunPassthrough(
		[]string{"git", "config", "--local", branchConfigKey(branch, key), value},
		opts...,
	)
}

// Uses `git config --get --default "" branch.<branch>.<key>`, which exits 0 with empty output when the key is missing.
// Git older than 2.18 doesn't support --default and exits non-zero instead, so this requires git 2.18+.
func GetBranchConfig(branch, key string, opts ...process.ExecOption) (string, error) {
	return process.GetOutput(
		[]string{"git", "config", "--get", "--default", "", branchConfigKey(branch, key)},
		opts...,
	)
}

func branchConfigKey(branch, key string) string {
	return "branch." + branch + "." + key
}

const badBooleanMarker = "bad boolean config value"

const keyNotFoundExitCode = 1

const unsetExitCode = 5 // "nothing to unset"

func GetRepoConfigBool(key string, opts ...process.ExecOption) (*bool, error) {
	output, err := process.GetOutput(
		[]string{"git", "config", "--type=bool", "--get", key},
		opts...,
	)
	if err != nil {
		var verr *process.VerboseExecError
		if errors.As(err, &verr) {
			if strings.Contains(verr.Stderr, badBooleanMarker) {
				return nil, nil
			}
			var exitErr *exec.ExitError
			if errors.As(verr.Err, &exitErr) && exitErr.ExitCode() == keyNotFoundExitCode {
				return nil, nil
			}
		}
		return nil, err
	}
	switch output {
	case "true":
		v := true
		return &v, nil
	case "false":
		v := false
		return &v, nil
	default:
		return nil, nil
	}
}

func SetRepoConfigBool(key string, value bool, opts ...process.ExecOption) error {
	literal := "false"
	if value {
		literal = "true"
	}
	return process.RunPassthrough(
		[]string{"git", "config", "--type=bool", "--local", key, literal},
		opts...,
	)
}

// Git exits 5 when the key was already unset; UnsetRepoConfig normalizes that case to a nil error so callers can call it idempotently
func UnsetRepoConfig(key string, opts ...process.ExecOption) error {
	err := process.RunPassthrough(
		[]string{"git", "config", "--local", "--unset", key},
		opts...,
	)
	if err == nil {
		return nil
	}
	var passErr *process.PassthroughError
	if errors.As(err, &passErr) && passErr.Code == unsetExitCode {
		return nil
	}
	return err
}

func FetchOrigin(opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "fetch", "origin"}, opts...)
}

// CheckoutDetach runs a plain `git checkout <ref>` — no --detach flag.
// HEAD only ends up detached because callers pass a ref that isn't a local branch, such as "origin/<default>"; that's git's own behavior for checking out a non-branch ref.
func CheckoutDetach(ref string, opts ...process.ExecOption) error {
	return process.RunPassthrough([]string{"git", "checkout", ref}, opts...)
}

func GenerateBranchName(prefix, taskName string) string {
	slug := slugify(taskName)
	if slug == "" {
		slug = unnamedSlug
	}

	var result string
	if prefix == "" {
		result = slug
	} else {
		result = prefix + "-" + slug
	}
	result = strings.ToLower(result)
	result = nonAlphaNum.ReplaceAllString(result, "-")
	result = strings.Trim(result, "-")

	if len(result) > maxBranchLength {
		result = result[:maxBranchLength]
		result = strings.TrimRight(result, "-")
	}
	return result
}

//  Used to check whether taskName is entirely non-ASCII-alphanumeric
func slugify(s string) string {
	lower := strings.ToLower(s)
	replaced := nonAlphaNum.ReplaceAllString(lower, "-")
	return strings.Trim(replaced, "-")
}
