macos_quit_when_last_window_closed yes
allow_remote_control yes
listen_on unix:/tmp/devora-kitty.sock

# Should be more than enough as the actual scrollback is handled by Neovim
scrollback_lines 0
font_size 15.0

include current-theme.conf

# Shortcuts
clear_all_shortcuts yes

## Workspace UI
map ctrl+s launch --type=tab --tab-title "Devora" --cwd=~ zsh --login --interactive -c "debi workspace-ui"
map ctrl+shift+s launch --type=tab --cwd=~
#map ctrl+s launch --type=overlay --cwd=~ zsh --login --interactive -c "debi workspace-ui"

## User Guide
map f1 launch --type=tab --tab-title "User Guide" zsh --login --interactive -c "glow --style $KITTY_CONFIG_DIRECTORY/glow-theme.json --pager $DEVORA_RESOURCES_DIR/USER_GUIDE.md"

## Tabs
map ctrl+left  previous_tab
map ctrl+right next_tab
map ctrl+shift+left  move_tab_backward
map ctrl+shift+right move_tab_forward

## Font size
map ctrl+equal change_font_size current +2.0
map ctrl+minus change_font_size current -2.0

map ctrl+1 set_font_size 12.0
map ctrl+2 set_font_size 15.0
map ctrl+3 set_font_size 26.0

## Clipboard
map ctrl+shift+v paste_from_clipboard
map cmd+v paste_from_clipboard

## Reload config
map ctrl+shift+r load_config_file
